### ISSUE TITLE
server.js post 500 error

### ISSUE THREAD

**Issue by coding2dawn** [theericzhang/OpenResponse#9]
I had set up this app successfully on my server and Vercel but when I tried to type something in the text area to send, it just showed this error:
Request Method: POST
Status Code: 500

**Comment by theericzhang** [comment]
Hey there! Sorry to hear about that, can you provide me with more information about your `.env`?

A 500 code may be attributed to an invalid API key - please make sure your `.env` is set up with a valid key and current environment, like so:

```
OPENAI_API_KEY=YOUR_KEY
CURRENT_ENVIRONMENT=openai
```

**Comment by coding2dawn** [comment]
Thank you for your reply.

It turns out that my OpenAI account didn't upgrade until I paid 20$.

Have a nice day.
